# vim ft=yaml
# travis-ci.org definition for Nimfa tests
language: python

sudo: false

cache:
 apt: true

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
python:
  - "2.7"
#  - "3.4"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pytest matplotlib Pillow
  - pip install pep8 python-coveralls pytest-cov
  - pip install -e .

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
  - wget http://files.grouplens.org/datasets/movielens/ml-100k.zip -P nimfa/datasets/MovieLens/
  - unzip -j nimfa/datasets/MovieLens/ml-100k.zip -d  nimfa/datasets/MovieLens/
  - wget http://cbcl.mit.edu/projects/cbcl/software-datasets/faces.tar.gz -P nimfa/datasets/CBCL_faces/
  - tar zxvf nimfa/datasets/CBCL_faces/faces.tar.gz -C nimfa/datasets/CBCL_faces/
  - tar zxvf nimfa/datasets/CBCL_faces/face.train.tar.gz -C nimfa/datasets/CBCL_faces/
  - mv nimfa/datasets/CBCL_faces/train/face/ nimfa/datasets/CBCL_faces/

script:
  - py.test --cov=nimfa

after_success:
  - coveralls

# TODO Later if you decide to upload tagged releases to pypi automagically
# see https://docs.travis-ci.com/user/deployment/pypi/ for details
#deploy:
#  provider: pypi
#  distributions: sdist
#  user: YOURUSERNAME
#  password:
#    secure: YOUR_ENCRYPTED_WITH_TRAVISTOOLS_PASSWORD_FOR_PYPI
#  on:
#    tags: true
#    branch: master
#    repo: YOURGITHUBLOGIN/nimfa
#    condition: "$TRAVIS_PYTHON_VERSION == 2.7 && $TRAVIS_TAG =~ ^v[0-9]*[.][.0-9]*"
